# Generated by Django 4.0.5 on 2022-10-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name_plural': 'perfis'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='titulo',
        ),
        migrations.AlterField(
            model_name='post',
            name='conteudo',
            field=models.CharField(max_length=200),
        ),
    ]
