# Generated by Django 4.1.2 on 2022-10-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_perfil_options_remove_post_titulo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-data_criacao'], 'verbose_name_plural': 'posts'},
        ),
        migrations.AddField(
            model_name='perfil',
            name='imagem',
            field=models.ImageField(blank=True, default='', upload_to='posts/imagens/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='conteudo',
            field=models.CharField(max_length=140),
        ),
    ]
