# Generated by Django 4.1.2 on 2022-11-13 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='favorita',
            field=models.ManyToManyField(to='posts.post'),
        ),
    ]
